### ISSUE TITLE
Website Redesign

### ISSUE THREAD

**Issue by AvgZing** [BoxOfDevs/boxofdevs.github.io#26]
In this message (Staff and contributors are free to edit this todo) we have: Todo list, and current plans. 

### NOTE: DO NOT DISCUSS THE WEBSITE REDESIGN ON DISCORD! KEEP DISCUSSIONS HERE!

# Plans
 - Host a frontend site with pages similar to our current one on github pages
 - Host a backend projects page, which will ideally have automatic phar building for each commit, along with a stable releases section and possibly even an auto-updater
 - Possible: Vue, Google Polymer, or something built from scratch (probably using jQuery)
 - Possible: Bulma for styling
 - Poll for frontend and backend ---- Backend: http://www.strawpoll.me/15014604  AND Frontend: http://www.strawpoll.me/15014615
 - Start from scratch to avoid having outdated frameworks
 - This is a redesign where all staff and active discord members have a say
 - Add more ad spaces

# ToDo
 - [ ] Decide on a theme
 - [ ] Decide on a framework
 - [ ] Decide on pages and their content
 - [ ] Code pages
 - [ ] Release the newly redesigned website

**Comment by AvgZing** [comment]
I, like @Ad5001, propose that we do everything from scratch as frameworks will quickly go outdated.

**Comment by lavender-sys** [comment]
I propose we use [Vue](https://vuejs.org) for a JS Framework, and [Bulma](https://bulma.io) for styling.

**Comment by ghost** [comment]
@TheRoyalBlock Uhh, React has been around since 2014 and is being actively maintained by Facebook. Why do we need auto-updaters and phar packagers, we have PocketMine Tools and DevTools for that. Just for reference “Bulma” is not a framework, it is a style library.

**Comment by lavender-sys** [comment]
> [Bulma](https://bulma.io) for styling. 

I did say we could use Bulma for styling.

**Comment by AvgZing** [comment]
Whooops with the Bulma thing

Also: We don't want people to rely on other sites for our plugins. Auto compilation is helpful.

**Comment by Ad5001** [comment]
> maintained by Facebook

That's the reason I don't code with React.

**Comment by HimbeersaftLP** [comment]
Considering that our projects "backend" would most likely be on some free host, I'd expect that to be less reliable than Poggit and GitHub.

**Comment by lavender-sys** [comment]
I tired React and didn’t even finish the tutorial.

**Comment by lavender-sys** [comment]
@HimbeersaftLP I have a $10/month DigitalOcean droplet. And yes, it’s on the new pricing, meaning 2GB of RAM.

**Comment by AvgZing** [comment]
@HimbeersaftLP It would be hosted on glitch. If we were to proceed with that idea, each plugin would have:

 - Auto updater
 - Auto compiler
 - Stable releases section (Manually mark a compiled build as stable)
 - Description

**Comment by ghost** [comment]
@HimbeersaftLP The “backend” would be located on Heroku or Glitch. Yes, they are free but they have a good reputation.

**Comment by SuperOP535** [comment]
bootstrap

**Comment by ghost** [comment]
We are talking about backend.

**Comment by SuperOP535** [comment]
And I'm doing about frontend 
![image](https://user-images.githubusercontent.com/27556391/35882786-96415814-0b85-11e8-81f9-05e5d73c5e54.png)

**Comment by HimbeersaftLP** [comment]
Poggit does have a good reputation too, when it doesn't come to the design and we don't need to reinvent the wheel for that (which, as by my experience, usually doesn't work out very well)

**Comment by SuperOP535** [comment]
glitch does have `phar` pre-installed

**Comment by AvgZing** [comment]
Poggit, however, doesn't have an auto-updater. We know that BOD is not good at maintaining and updated plugins, an auto updater is basically a necessity

**Comment by lavender-sys** [comment]
And we’re talking about backend.
 _insert image_

**Comment by SuperOP535** [comment]
![image](https://user-images.githubusercontent.com/27556391/35882873-d4ab0780-0b85-11e8-923d-a17e1c6f81a8.png)

**Comment by ghost** [comment]
This is my timeline as someone who has been working with this for while.
@TheRoyalBlock @Dog2puppy 
- [ ] Select a backend language. (Node.js or Go)
- [ ] Select a fronted framework. (Vue or Handlebars)
- [ ] Work on the wireframe using invisionapp.com.
- [ ] Start a Glitch project and invite everyone.
- [ ] Begin development of the frontend.
- [ ] Begin development of the backend.
- [ ] Release Website

**Comment by SuperOP535** [comment]
why not php

**Comment by lavender-sys** [comment]
_light bulb appears_ 💡

We could create an API server using Node.js and Express. For front end, we make a SPA (single page web app) using Vue. In Vue, we would fetch data from the API and render it! And also, Vue supports GitHub Pages.

**Comment by ghost** [comment]
That language honestly has too many security concerns and is not a modern language, Node.js and Go are modern.

**Comment by ghost** [comment]
@Dog2puppy Agreed. We can build it as a static site, that is a great idea.

**Comment by AvgZing** [comment]
@nathfreder 

1. We will not have a backend page, it's been decided by staff on discord
2. Frontend and wireframe will likely be coded from scratch to avoid going outdated
3. No usage of glitch, everything will be on github pages

**Comment by SuperOP535** [comment]
blah blah php is awesome

**Comment by lavender-sys** [comment]
@nathfreder What’s Invision App?

**Comment by SuperOP535** [comment]
no wait! we can use Java!!!!!!11!1!1

**Comment by SuperOP535** [comment]
java -jar boxofdevs.jar

**Comment by Ad5001** [comment]
Hey, why not make our own linux distro which would include an hardcoded Assembly made webserver hosting our website?

**Comment by lavender-sys** [comment]
@TheRoyalBlock What discussion is this? I was never invited.

**Comment by HimbeersaftLP** [comment]
@Ad5001 Why not write it in brainfuck and compile for a Microcontroller that connects via a serial interface to a dial-up modem?

**Comment by SuperOP535** [comment]
jQuery ftw

**Comment by SuperOP535** [comment]
write it in BIT, here is a hello world program:
```
LINENUMBERZEROCODEPRINTZEROGOTOONELINENUMBERONECODEPRINTONEGOTOONEZEROLINENUMBE
RONEZEROCODEPRINTZEROGOTOONEONELINENUMBERONEONECODEPRINTZEROGOTOONEZEROZEROLINE
NUMBERONEZEROZEROCODEPRINTONEGOTOONEZEROONELINENUMBERONEZEROONECODEPRINTZEROGOT
OONEONEZEROLINENUMBERONEONEZEROCODEPRINTZEROGOTOONEONEONELINENUMBERONEONEONECOD
EPRINTZEROGOTOONEZEROZEROZEROLINENUMBERONEZEROZEROZEROCODEPRINTZEROGOTOONEZEROZ
EROONELINENUMBERONEZEROZEROONECODEPRINTONEGOTOONEZEROONEZEROLINENUMBERONEZEROON
EZEROCODEPRINTONEGOTOONEZEROONEONELINENUMBERONEZEROONEONECODEPRINTZEROGOTOONEON
EZEROZEROLINENUMBERONEONEZEROZEROCODEPRINTZEROGOTOONEONEZEROONELINENUMBERONEONE
ZEROONECODEPRINTONEGOTOONEONEONEZEROLINENUMBERONEONEONEZEROCODEPRINTZEROGOTOONE
ONEONEONELINENUMBERONEONEONEONECODEPRINTONEGOTOONEZEROZEROZEROZEROLINENUMBERONE
ZEROZEROZEROZEROCODEPRINTZEROGOTOONEZEROZEROZEROONELINENUMBERONEZEROZEROZEROONE
CODEPRINTONEGOTOONEZEROZEROONEZEROLINENUMBERONEZEROZEROONEZEROCODEPRINTONEGOTOO
NEZEROZEROONEONELINENUMBERONEZEROZEROONEONECODEPRINTZEROGOTOONEZEROONEZEROZEROL
INENUMBERONEZEROONEZEROZEROCODEPRINTONEGOTOONEZEROONEZEROONELINENUMBERONEZEROON
EZEROONECODEPRINTONEGOTOONEZEROONEONEZEROLINENUMBERONEZEROONEONEZEROCODEPRINTZE
ROGOTOONEZEROONEONEONELINENUMBERONEZEROONEONEONECODEPRINTZEROGOTOONEONEZEROZERO
ZEROLINENUMBERONEONEZEROZEROZEROCODEPRINTZEROGOTOONEONEZEROZEROONELINENUMBERONE
ONEZEROZEROONECODEPRINTONEGOTOONEONEZEROONEZEROLINENUMBERONEONEZEROONEZEROCODEP
RINTONEGOTOONEONEZEROONEONELINENUMBERONEONEZEROONEONECODEPRINTZEROGOTOONEONEONE
ZEROZEROLINENUMBERONEONEONEZEROZEROCODEPRINTONEGOTOONEONEONEZEROONELINENUMBERON
EONEONEZEROONECODEPRINTONEGOTOONEONEONEONEZEROLINENUMBERONEONEONEONEZEROCODEPRI
NTZEROGOTOONEONEONEONEONELINENUMBERONEONEONEONEONECODEPRINTZEROGOTOONEZEROZEROZ
EROZEROZEROLINENUMBERONEZEROZEROZEROZEROZEROCODEPRINTZEROGOTOONEZEROZEROZEROZER
OONELINENUMBERONEZEROZEROZEROZEROONECODEPRINTONEGOTOONEZEROZEROZEROONEZEROLINEN
UMBERONEZEROZEROZEROONEZEROCODEPRINTONEGOTOONEZEROZEROZEROONEONELINENUMBERONEZE
ROZEROZEROONEONECODEPRINTZEROGOTOONEZEROZEROONEZEROZEROLINENUMBERONEZEROZEROONE
ZEROZEROCODEPRINTONEGOTOONEZEROZEROONEZEROONELINENUMBERONEZEROZEROONEZEROONECOD
EPRINTONEGOTOONEZEROZEROONEONEZEROLINENUMBERONEZEROZEROONEONEZEROCODEPRINTONEGO
TOONEZEROZEROONEONEONELINENUMBERONEZEROZEROONEONEONECODEPRINTONEGOTOONEZEROONEZ
EROZEROZEROLINENUMBERONEZEROONEZEROZEROZEROCODEPRINTZEROGOTOONEZEROONEZEROZEROO
NELINENUMBERONEZEROONEZEROZEROONECODEPRINTZEROGOTOONEZEROONEZEROONEZEROLINENUMB
ERONEZEROONEZEROONEZEROCODEPRINTONEGOTOONEZEROONEZEROONEONELINENUMBERONEZEROONE
ZEROONEONECODEPRINTZEROGOTOONEZEROONEONEZEROZEROLINENUMBERONEZEROONEONEZEROZERO
CODEPRINTZEROGOTOONEZEROONEONEZEROONELINENUMBERONEZEROONEONEZEROONECODEPRINTZER
OGOTOONEZEROONEONEONEZEROLINENUMBERONEZEROONEONEONEZEROCODEPRINTZEROGOTOONEZERO
ONEONEONEONELINENUMBERONEZEROONEONEONEONECODEPRINTZEROGOTOONEONEZEROZEROZEROZER
OLINENUMBERONEONEZEROZEROZEROZEROCODEPRINTZEROGOTOONEONEZEROZEROZEROONELINENUMB
ERONEONEZEROZEROZEROONECODEPRINTONEGOTOONEONEZEROZEROONEZEROLINENUMBERONEONEZER
OZEROONEZEROCODEPRINTONEGOTOONEONEZEROZEROONEONELINENUMBERONEONEZEROZEROONEONEC
ODEPRINTONEGOTOONEONEZEROONEZEROZEROLINENUMBERONEONEZEROONEZEROZEROCODEPRINTZER
OGOTOONEONEZEROONEZEROONELINENUMBERONEONEZEROONEZEROONECODEPRINTONEGOTOONEONEZE
ROONEONEZEROLINENUMBERONEONEZEROONEONEZEROCODEPRINTONEGOTOONEONEZEROONEONEONELI
NENUMBERONEONEZEROONEONEONECODEPRINTONEGOTOONEONEONEZEROZEROZEROLINENUMBERONEON
EONEZEROZEROZEROCODEPRINTZEROGOTOONEONEONEZEROZEROONELINENUMBERONEONEONEZEROZER
OONECODEPRINTONEGOTOONEONEONEZEROONEZEROLINENUMBERONEONEONEZEROONEZEROCODEPRINT
ONEGOTOONEONEONEZEROONEONELINENUMBERONEONEONEZEROONEONECODEPRINTZEROGOTOONEONEO
NEONEZEROZEROLINENUMBERONEONEONEONEZEROZEROCODEPRINTONEGOTOONEONEONEONEZEROONEL
INENUMBERONEONEONEONEZEROONECODEPRINTONEGOTOONEONEONEONEONEZEROLINENUMBERONEONE
ONEONEONEZEROCODEPRINTONEGOTOONEONEONEONEONEONELINENUMBERONEONEONEONEONEONECODE
PRINTONEGOTOONEZEROZEROZEROZEROZEROZEROLINENUMBERONEZEROZEROZEROZEROZEROZEROCOD
EPRINTZEROGOTOONEZEROZEROZEROZEROZEROONELINENUMBERONEZEROZEROZEROZEROZEROONECOD
EPRINTONEGOTOONEZEROZEROZEROZEROONEZEROLINENUMBERONEZEROZEROZEROZEROONEZEROCODE
PRINTONEGOTOONEZEROZEROZEROZEROONEONELINENUMBERONEZEROZEROZEROZEROONEONECODEPRI
NTONEGOTOONEZEROZEROZEROONEZEROZEROLINENUMBERONEZEROZEROZEROONEZEROZEROCODEPRIN
TZEROGOTOONEZEROZEROZEROONEZEROONELINENUMBERONEZEROZEROZEROONEZEROONECODEPRINTZ
EROGOTOONEZEROZEROZEROONEONEZEROLINENUMBERONEZEROZEROZEROONEONEZEROCODEPRINTONE
GOTOONEZEROZEROZEROONEONEONELINENUMBERONEZEROZEROZEROONEONEONECODEPRINTZEROGOTO
ONEZEROZEROONEZEROZEROZEROLINENUMBERONEZEROZEROONEZEROZEROZEROCODEPRINTZEROGOTO
ONEZEROZEROONEZEROZEROONELINENUMBERONEZEROZEROONEZEROZEROONECODEPRINTONEGOTOONE
ZEROZEROONEZEROONEZEROLINENUMBERONEZEROZEROONEZEROONEZEROCODEPRINTONEGOTOONEZER
OZEROONEZEROONEONELINENUMBERONEZEROZEROONEZEROONEONECODEPRINTZEROGOTOONEZEROZER
OONEONEZEROZEROLINENUMBERONEZEROZEROONEONEZEROZEROCODEPRINTONEGOTOONEZEROZEROON
EONEZEROONELINENUMBERONEZEROZEROONEONEZEROONECODEPRINTONEGOTOONEZEROZEROONEONEO
NEZEROLINENUMBERONEZEROZEROONEONEONEZEROCODEPRINTZEROGOTOONEZEROZEROONEONEONEON
ELINENUMBERONEZEROZEROONEONEONEONECODEPRINTZEROGOTOONEZEROONEZEROZEROZEROZEROLI
NENUMBERONEZEROONEZEROZEROZEROZEROCODEPRINTZEROGOTOONEZEROONEZEROZEROZEROONELIN
ENUMBERONEZEROONEZEROZEROZEROONECODEPRINTONEGOTOONEZEROONEZEROZEROONEZEROLINENU
MBERONEZEROONEZEROZEROONEZEROCODEPRINTONEGOTOONEZEROONEZEROZEROONEONELINENUMBER
ONEZEROONEZEROZEROONEONECODEPRINTZEROGOTOONEZEROONEZEROONEZEROZEROLINENUMBERONE
ZEROONEZEROONEZEROZEROCODEPRINTZEROGOTOONEZEROONEZEROONEZEROONELINENUMBERONEZER
OONEZEROONEZEROONECODEPRINTONEGOTOONEZEROONEZEROONEONEZEROLINENUMBERONEZEROONEZ
EROONEONEZEROCODEPRINTZEROGOTOONEZEROONEZEROONEONEONELINENUMBERONEZEROONEZEROON
EONEONECODEPRINTZEROGOTOONEZEROONEONEZEROZEROZEROLINENUMBERONEZEROONEONEZEROZER
OZEROCODEPRINTZEROGOTOONEZEROONEONEZEROZEROONELINENUMBERONEZEROONEONEZEROZEROON
ECODEPRINTZEROGOTOONEZEROONEONEZEROONEZEROLINENUMBERONEZEROONEONEZEROONEZEROCOD
EPRINTONEGOTOONEZEROONEONEZEROONEONELINENUMBERONEZEROONEONEZEROONEONECODEPRINTZ
EROGOTOONEZEROONEONEONEZEROZEROLINENUMBERONEZEROONEONEONEZEROZEROCODEPRINTZEROG
OTOONEZEROONEONEONEZEROONELINENUMBERONEZEROONEONEONEZEROONECODEPRINTZEROGOTOONE
ZEROONEONEONEONEZEROLINENUMBERONEZEROONEONEONEONEZEROCODEPRINTZEROGOTOONEZEROON
EONEONEONEONELINENUMBERONEZEROONEONEONEONEONECODEPRINTONE```

**Comment by ghost** [comment]
@TheRoyalBlock What is a backend, explain it to me. The term “backend page” does not make sense.

**Comment by ghost** [comment]
The current website has a backend, in case you did not know.

**Comment by AvgZing** [comment]
FFS NATE STOP GOING ON ABOUT BACKEND! WE'RE NOT HAVING IT!

I said backend page because the majority of the website would be static frontend, no backend, and only one page would have some backend *and* frontend.

**Comment by ghost** [comment]
@TheRoyalBlock NO, EXPLAIN TO ME IF YOU EVEN KNOW WHAT IT IS. YOU ARE GOING TO HAVE TO TRASH YOUR OWN SITE SINCE IT HAS A BACKEND TOO.

**Comment by ghost** [comment]
_srry for caps_

**Comment by AvgZing** [comment]
I am trashing my own site.

**Comment by SuperOP535** [comment]
this is the best conversation ever

**Comment by ghost** [comment]
@TheRoyalBlock Well since you are anti-backend boxofdevs.com must go.

**Comment by AvgZing** [comment]
boxofdevs.com *is* going, that's what this conversation is all about.

**Comment by lavender-sys** [comment]
We’re having a backend!!!

**Comment by ghost** [comment]
@TheRoyalBlock Yeah, but why get rid of things that are already there?

**Comment by SuperOP535** [comment]
I've made an archive just incase someone decides to remove the comments, https://web.archive.org/web/20180206205127/https://github.com/BoxOfDevs/boxofdevs.github.io/issues/26 ~~one day we will look on this and remember~~

**Comment by ghost** [comment]
Lol

**Comment by AvgZing** [comment]
@SuperOP535 Most of these will be removed in a few days, but an archive is already in #status on discord

**Comment by dragonwocky** [comment]
Seriously.... **We don't need to do our own backend.**

The only thing we might need it for is auto-compiling .phars - and we don't actually need or want that.

@TheRoyalBlock said "BOD is not good at maintaining and updated plugins" - true. Why would we need to auto-compile updates when there is nothing *to* update?

These points and others, as AvgZing said, were discussed in the staff channel on Discord, and yes - we don't need our own backend. For what we need, GitHub Pages is good enough...

**Comment by ghost** [comment]
@TheRoyalBlock Why, open source is meant to be open?

**Comment by ghost** [comment]
@TheDragonRing How about this, we do the frontend then evaluate about the backend.

**Comment by AvgZing** [comment]
Just an offtopic heads up: My messages on discord aren't sending at all, don't try to have a convo on there with me. @nathfreder Why to what? The posts will be removed because they're offtopic. And also, IT IS AN OFFICIAL DECISION THAT WE'RE NOT DOING OUR OWN BACKEND. DON'T TRY TO OVERRIDE IT, @nathfreder. YOU'RE NOT EVEN PART OF THE STAFF! Anyways, that's a good idea.

**Comment by ghost** [comment]
[removed by nathfreder]

**Comment by lavender-sys** [comment]
I am part of staff. I’m arguing _with_ @nathfreder. I think we need a backend ~~to torture @TheRoyalBlock with writing JS~~ because... It’ll be a good learning experience.

**Comment by AvgZing** [comment]
I think i'm just gonna step out of this conversation now.

**Comment by ghost** [comment]
You guys can not do a backend, but I will do one on my own and make a optional pull request. @TheRoyalBlock, is that okay?

**Comment by ghost** [comment]
@TheRoyalBlock We need your input too.

**Comment by lavender-sys** [comment]
I think I made them mad. _slowly walks away_

**Comment by ghost** [comment]
@Dog2puppy it is my fault, i think that it would be a good idea not to mention backend at all. If it is an official decision it is not my website to change.

**Comment by HimbeersaftLP** [comment]
@nathfreder What would you want that backend to do?

(to be clear, by backend I don't mean a webserver that just serves static files)

**Comment by lavender-sys** [comment]
Should I make a new branch named develop?

**Comment by ghost** [comment]
@HimbeersaftLP I would like to use it for auto staff updates, news, projects updater, etc.

**Comment by ghost** [comment]
@Dog2puppy Can you invite me to boxofdevs.github.io repository, as a contributor so that I can add to the develop branch.

**Comment by lavender-sys** [comment]
@TheRoyalBlock said no. 😢

**Comment by AvgZing** [comment]
And I said that for a reason. 
We have total-revamp branch (Thanks @TheDragonRing). 
Also, @nathfreder, we're nowhere near actually coding it. We haven't even come up with a design and framework yet!

**Comment by lavender-sys** [comment]
And if we had Vue, it could be a SPA.

**Comment by lavender-sys** [comment]
Or, we could just use the built in Jekyll templating.

**Comment by ghost** [comment]
@Dog2puppy That is not needed and needs Ruby to even test.  @TheRoyalBlock good point

**Comment by dragonwocky** [comment]
@BoxOfDevs/members @nathfreder @SuperOP535 let me clear this up.

The entire idea of having a backend in the first place was based on a misunderstanding, an old post that most people had forgotten about / were ignoring. We aren't actually having a blog (there's nothing to post on one).

Then it turned into the idea that we might need to auto-compile projects, but as I pointed out earlier - we have nothing to auto-compile, and even if we did, I'm not sure users would actually want to use not-yet-functional half-coded versions of updates. For plugins, we can manually use Poggit and GitHub releases, and for other projects either they won't need compiling (frontend web projects), or they'll be a kind of project we haven't yet considered, and so we'll deal with that when we come to it.

Now it seems mainly just that some people want a backend (for what reason I'm no longer sure), and it's turned into an argument with seemingly no solution.

Let's just get the frontend done first, as  @@nathfreder said, then we will hopefully realise that we don't need a backend.

Oh, and BTW? What's all this about boxofdevs.com going? At the moment, since the domain hasn't expired, we might as well use it. When it does expire, I may renew it or we may just stick with boxofdevs.github.io - either way, I'm not sure what that has to do with this...

P.S. Yes, as @TheRoyalBlock said, I made a branch called total-revamp. I'm working on a commit that's almost finished, then once it's done (adds a few basics and things like jQuery + FontAwesome), we can start planning what we want the site to end up looking like.

Edit: That commit has now been pushed. At the moment, the jQuery and FontAwesome files are there ready to use, but later on they may be changed to CDNs. See the commit here: https://github.com/BoxOfDevs/boxofdevs.github.io/commit/089c0e00e5acbff43bed095327add39b7906e0df

**Comment by lavender-sys** [comment]
@nathfreder GitHub Pages supports Jekyll built in and really Ruby knowledge isn’t needed. The reason you would use it on GitHub Pages is for things like changing a Navbar. Do you want to change all 10 or 100 or even more pages just to update the Navbar, when you could simply change 1 file.

**Comment by ghost** [comment]
@Dog2puppy That is if you use a theme, if you want to build your on Jenkyll site you need Ruby Gems to compile it, then when you upload to GitHub it will be built again by GitHub.

**Comment by ghost** [comment]
@TheDragonRing Can you invite me as a contributor to the boxofdevs.github.io repo?

**Comment by lavender-sys** [comment]
@nathfreder You don't **need** to use a GitHub theme. You **can** use a GitHub theme. Take for example [Dog2puppy/dog2puppy.github.io](https://github.com/Dog2puppy/dog2puppy.github.io)

**Comment by ghost** [comment]
@Dog2puppy We want to design the site for ourself, not use a crummy theme.

**Comment by ghost** [comment]
@TheDragonRing We can re-design the website, then I will make a logo in Adobe AI that is not stolen https://dartstorage.co/product/large-box

**Comment by lavender-sys** [comment]
Yet, my own site doesn't use a theme. (Bulma is just styling)

**Comment by ghost** [comment]
@Dog2puppy I do not like Bulma, we are design the website as a group not from a library. BTW your site is offline.

**Comment by lavender-sys** [comment]
https://dog2puppy.github.io/

**Comment by ghost** [comment]
Oh, I was using dog2puppy.tk

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lavender-sys** [comment]
Our box is stolen? Who is responsible for this? @BoxOfDevs/members 

![MY BOX!](https://user-images.githubusercontent.com/13684891/35889281-f0dad6be-0b68-11e8-8c93-733dcb104049.png)


# THIS IS MY BOX!!!!!

**Comment by AvgZing** [comment]
NAH NAH NAH OURS DOESn"T HAVE A SHADOW

**Comment by AvgZing** [comment]
AND OURS IS A PNG

**Comment by lavender-sys** [comment]
![MY BOX!](https://user-images.githubusercontent.com/13684891/35889281-f0dad6be-0b68-11e8-8c93-733dcb104049.png)


# THIS IS MY BOX!!!!!

**Comment by lavender-sys** [comment]
![image](https://user-images.githubusercontent.com/13684891/35889560-10607998-0b6a-11e8-95dd-2d7868db835c.png)
**I SEE TONS OF SHADOWS!!!**

**Comment by AvgZing** [comment]
Sh

**Comment by lavender-sys** [comment]
@TheRoyalBlock Do you have any JS experience?

**Comment by SuperOP535** [comment]
@TheDragonRing I were talking about frontend but they made me confused

**Comment by dragonwocky** [comment]
@SuperOP535 yeah dw. Everybody was a bit confused.
@Dog2puppy erhm... the image was originally off a Google search I think... we didn't discover it was stolen until recently-ish... and the one with the shadow is the old version...

**Comment by dragonwocky** [comment]
@BoxOfDevs/members @SuperOP535 @nathfreder change of plans. So that we can see the new site @ [new.boxofdevs.com](https://new.boxofdevs.com) it will be in [this repo](https://github.com/BoxOfDevs/new-site).

**Comment by lavender-sys** [comment]
And if you want to see what I'm doing using Jekyll, you can see it [here](https://github.com/Dog2puppy/new-site) and the finished design [here](https://dog2puppy.github.io/new-site/).

**Comment by ghost** [comment]
@TheDragonRing Alright, now can someone please invite me to the repo.

**Comment by dragonwocky** [comment]
@nathfreder I'll add you, but since multiple people will be working on it at once please don't commit directly, use pull requests - even the BOD members are using them.

**Comment by ghost** [comment]
Alright. Sound good.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lavender-sys** [comment]
Closing this because we have a new repo.
